### ISSUE TITLE
Selectors should be casted to string in polyfills

### ISSUE THREAD

**Issue by aguingand** [mrhenry/core-web#1566]
## Expected Behavior
When providing an array to `querySelectorAll()`, the browser implicitly casts it to string e.g. So should polyfilled methods.

```js
document.querySelectorAll(['a', 'p']) /* is equivalent to */ 
document.querySelectorAll('a,p') /* because */ 
['a', 'p'].toString() === "a,p"
```

## Current Behavior
Some polyfill like:

https://github.com/mrhenry/core-web/blob/724df43cb5246e1b8c4a2a9ea789182142efa75a/packages/core-web/modules/~element-qsa-has.js#L451

Fails with `selector.toLowercase is not a function` when an array is provided.

## Possible Solution
Cast selectors at the beginning of polyfill functions.

## Steps to Reproduce
1. import `core-web/modules/~element-qsa-has`
2. call `document.querySelectorAll(['a', 'p'])`

## Context (Environment)
I'm using Alpine.js which calls `querySelectorAll` with an array
https://github.com/alpinejs/alpine/blob/dff0e3f950d314d39aff73d60e80b087bb6166ed/packages/alpinejs/src/lifecycle.js#L29

## Possible Implementation
Prepend polyfills with
```js
selectors = String(selectors);
```

**Comment by romainmenke** [comment]
Interesting!
Thank you for the report.

```js
document.querySelector({toString: ()=> { return 'body' }});
// <body>
```

**Comment by romainmenke** [comment]
@aguingand Can you try with version `1.1.2`?

**Comment by aguingand** [comment]
Seems good to me 👍

**Comment by romainmenke** [comment]
Awesome!

Thank you again for the very clear bug report 🙇
