### ISSUE TITLE
Added unnecessary polyfills / Unable to correctly parse some browserslist queries

### ISSUE THREAD

**Issue by AnYiEE** [mrhenry/core-web#1745]
I am using your `babel-plugin-core-web` in my project and it is functioning well. However, I have encountered a minor issue that I am unsure if it is feature or a bug.

When the source code includes `const abortController = new AbortController()`, an additional polyfill for the `fetch()` method is added, even when `fetch()` is not used. Is this feature? It appears that `AbortController` can be polyfilled separately, similar to what has been done in [this package](https://www.npmjs.com/package/abortcontroller-polyfill) with `dist/abortcontroller-polyfill-only.js`.

Furthermore, I do not fully comprehend why those [browser names](https://github.com/browserslist/browserslist#browsers) are not used. To utilize it correctly, I must follow [this approach](https://github.com/AnYiEE/AwesomeGadgets/blob/master/scripts/modules/utils/build-util.ts#L130).

**Comment by AnYiEE** [comment]
@romainmenke Thank you for your reply.

Yes, I have tried passing `browserslist`. But, I [directly call](https://github.com/AnYiEE/AwesomeGadgets/blob/master/scripts/modules/utils/build-util.ts#L233) the `babel.transformAsync` method instead of `module.exports` as in the example you provided, it seems that `babel-plugin-core-web` cannot obtain the correct browserslist and throws an error as follows:

```
node_modules\.pnpm\@mrhenry+core-web@1.2.0\node_modules\@mrhenry\core-web\lib\index.js:300
    throw new Error(`Unexpected browserslist result ${range}\nplease file an issue at https://github.com/mrhenry/core-web/issues`);
          ^

Error: [BABEL]: Unexpected browserslist result safari TP
please file an issue at https://github.com/mrhenry/core-web/issues (While processing: "D:\\GitRepository\\AwesomeGadgets\\node_modules\\.pnpm\\@mrhenry+babel-plugin-core-web@1.2.0\\node_modules\\@mrhenry\\babel-plugin-core-web\\lib\\index.js")
    at parseRange (node_modules\.pnpm\@mrhenry+core-web@1.2.0\node_modules\@mrhenry\core-web\lib\index.js:300:11)
    at node_modules\.pnpm\@mrhenry+core-web@1.2.0\node_modules\@mrhenry\core-web\lib\index.js:69:61
    at Array.map (<anonymous>)
    at required (node_modules\.pnpm\@mrhenry+core-web@1.2.0\node_modules\@mrhenry\core-web\lib\index.js:69:52)
    at module.exports (node_modules\.pnpm\@mrhenry+babel-plugin-core-web@1.2.0\node_modules\@mrhenry\babel-plugin-core-web\lib\index.js:5:21)
    at async (node_modules\.pnpm\@babel+core@7.23.5\node_modules\@babel\core\lib\gensync-utils\async.js:35:33)
...
```

Then, I directly pass [the browserslist in the project](https://github.com/AnYiEE/AwesomeGadgets/blob/master/.browserslistrc#L4) to it, like this:

```
plugins: [
	["@mrhenry/core-web", {
		browserslist: [
			"fully supports es5 and not dead",
		]
	}]
]
```

I received the same error as above (`Unexpected browserslist result ${range}\nplease file an issue at https://github.com/mrhenry/core-web/issues`), but I tried using the browserslist strings example like yours, and it can parse correctly.

So, I had to passing it the "browsers" option instead, but it seems there are also some issues as certain browser names cannot be matched one-to-one, resulting in the inability to correctly polyfill.

A polyfill for the `fetch()` method will be added [using caniuse-api](https://github.com/AnYiEE/AwesomeGadgets/commit/01df083436c10deb521feadd85c2f910402cd577#diff-24b209f31581271c364962374ac1f521b83660c98f29733eee21b7afe4e6e607R58) (browserslist is `defaults`). However, after browser name conversion, `babel-plugin-core-web` [does not think it is necessary](https://www.qiuwenbaike.cn/index.php?title=MediaWiki:Gadget-Wikiplus.js&diff=prev&oldid=6961771).

**Comment by AnYiEE** [comment]
> You can try to use an `ignore` comment

Comments have no effect on me.

Because I first use esbuild to process the imports in the source code, and then pass the output code to Babel. Since esbuild only keeps comments in [a specific format](https://esbuild.github.io/api/#legal-comments), like this `/*! core-web-ignore @mrhenry/core-web/modules/fetch */`, if it is just `/* core-web-ignore @mrhenry/core-web/modules/fetch */`, the code obtained by Babel will not contain any comments.

I changed the comment to `/*! core-web-ignore @mrhenry/core-web/modules/fetch */`, but it seems that `babel-plugin-core-web` does not recognize this.

If there could be an option, that would be great.

**Comment by AnYiEE** [comment]
I also tried this source code, set .browserslistrc to `> 0.1%` and pass browserslist to `babel-plugin-core-web` directly.

```
const audioContext = new AudioContext();
console.log(audioContext);
```

```
plugins: [
	[
		'@mrhenry/core-web',
		{
			browserslist: ['> 0.1%'],
		},
	],
],
```

The added polyfills only includes `@mrhenry/core-web/modules/console.js` and `@mrhenry/core-web/modules/console.log.js`, but due to [my own handling](https://github.com/AnYiEE/AwesomeGadgets/blob/57b5e1e16b11f1393c6d0766af9970bac82a78a6/scripts/modules/babel-plugin-import-polyfills.ts#L73) (using `caniuse-api`), the `audio-context-polyfill/AudioContext.js` is imported, while [this one](https://github.com/mrhenry/core-web/blob/main/packages/core-web/modules/AudioContext.js) in the repo is not.

**Comment by romainmenke** [comment]
@AnYiEE I've split the multiple items out into different issues to make them more actionable.

I think it's best if I first try to resolve those before continuing.

**Comment by AnYiEE** [comment]
@romainmenke Sorry for asking too many in one issue.

> I also tried this source code, set .browserslistrc to > 0.1% and pass browserslist to babel-plugin-core-web directly.

Similarly, I tried the following code:

```
const d = Intl.DateTimeFormat('en-US', {
	year: 'numeric',
	month: 'long',
	day: 'numeric',
	hour: 'numeric',
	minute: 'numeric',
	second: 'numeric',
	hour12: false,
}).format(new Date());
console.log(d);
```

`console` is polyfilled, but `Intl` not, is this feature?

**Comment by romainmenke** [comment]
> Sorry for asking too many in one issue.

It is always better to open a new issue :)
I've been doing that for you, but it would be helpful if you can do that from the start 🙇

**Comment by AnYiEE** [comment]
Currently, I have found that all the issues have been split into separate ones, so I will close this one for now. Thank you again for your patient response.

**Comment by romainmenke** [comment]
@AnYiEE I've just released a new version of all packages.
