### ISSUE TITLE
`new Blob()` is polyfilled using Blob.js, but the `stream` and `text` method are missing

### ISSUE THREAD

**Issue by AnYiEE** [mrhenry/core-web#1760]
## Missing polyfill

https://caniuse.com/mdn-api_blob_stream
https://caniuse.com/mdn-api_blob_text

## Feature specification

https://developer.mozilla.org/en-US/docs/Web/API/Blob/stream
https://developer.mozilla.org/en-US/docs/Web/API/Blob/text

## Existing polyfill implementation

https://github.com/bjornstar/blob-polyfill

**Comment by romainmenke** [comment]
There is an upstream issue for this that you can subscribe to : https://github.com/JakeChampion/polyfill-library/issues/532

**Comment by AnYiEE** [comment]
@romainmenke I can add other polyfills with these methods myself, but how do I prevent babel-plugin-core-web from adding a polyfill for Blob? I cannot add comments to each file because I can only control the compilation process and not what is written.

**Comment by romainmenke** [comment]
That is not a use case we support.

You can either create a similar tool to `core-web` that works exactly as you want it too.
Or you can contribute upstream in `polyfill-library`.

We obviously prefer to add and fix polyfills upstream :)

**Comment by AnYiEE** [comment]
Instead of reinventing the wheel, I simply made [a minor patch](https://github.com/AnYiEE/AwesomeGadgets/commit/3fe3401) to it because it already has capabilities in handling AST and other aspects.

**Comment by romainmenke** [comment]
I can not stress this enough, but fixing this upstream in `polyfill-library` is the better way to resolve these issues :)

Then you are neither reinventing the wheel nor needing to maintain very specific patches :)
