### ISSUE TITLE
Exception cause on using `in` keyword to search member on undefined

### ISSUE THREAD

**Issue by vcup** [mrhenry/core-web#1795]
As title, In my scenario, `window` and `self` is not availble on global, but the `global` and `globalThis` is availble on global.
I'm using core-web for Wechat Miniprogram, it'll running render stuff and javascript codes in separeted threads, and `self` and `window` are not available for core-web.

I also thinking this is probably occur in other frameworks that has similar behavior.
However `global` and `globalThis` is availble so we can still polyfill something.

I think we can just simplelly check `window` and `self` is available before using `in` keyword to search member on them.
like this:
```javascript
if (!self || !("TextEncoder"in self&&"TextDecoder"in self) { /* ... */ }
```

To simulate this behavior, just claim a variable call `self` and `window` with an `undefiend` value, forgive me not following the issue template, this is not quite complex issue.
<details>
<summary>Screenshots</summary>

![image](https://github.com/mrhenry/core-web/assets/53596976/ea5c4a03-6a15-46ed-8ebe-86ba47f371b7)

After adding check for TextDecoder.js
![image](https://github.com/mrhenry/core-web/assets/53596976/a85dd2ec-972d-471a-a6af-5edca7933284)

</details>
I'm just using `TextDecoder`, I think the same issues also happen elsewhere.

**Comment by vcup** [comment]
I use a regex follow to search and replace all matched result in files on `node_modules/@mrhenry/core-web`
search term: `(!\("\w+"in self)`
replace to: `!self||$1`
Its work well for me.

**Comment by fd** [comment]
Just to reiterate, you are running some code in a WebWorker/background-thread? In that case the `window` global would not be available. I believe some polyfills just assume they are used on the main loop which does have `window`. 🤔 

@romainmenke thoughts?

**Comment by romainmenke** [comment]
`self` is available in web workers, so I don't think the context mentioned in the OP is a web standard context. 

We can only support web standard stuff.

@vcup Can you provide references as to your context and the web standards or docs that describe these?

**Comment by vcup** [comment]
Sorry for late response, I think my environment that using this library is not a web standard stuff, maybe I can only write some script to replace library files with regex on `node_modules/`, and run it after `npm install`.
