### ISSUE TITLE
Error thrown in Intl.js casuing polyfill.io failure

### ISSUE THREAD

**Issue by sundy001** [mrhenry/core-web#43]
I've got the following error from polyfill.io started from UTC 26-2-2020 14:00 on IE11. 
```
Locale 'af-NA.js' is not well-formed
```

I found that the error is caused by the new checking in [intl.js](https://github.com/mrhenry/core-web/blame/9927bf28e2157c10411af82b0fa1d1ea101a20b3/packages/core-web/modules/Intl.js#L7) According to my understanding, the error is caused by an incorrect format of locales arguments provided to `Intl.NumberFormat.supportedLocalesOf` function.

Could you take a look? Thanks!!

**Comment by romainmenke** [comment]
Hi!

Thank you for filing an issue. 

We noticed this too and submitted a fix upstream in polyfill-library :

https://github.com/Financial-Times/polyfill-library/pull/499

It is probably best to use `v0.0.5` if you depend on intl.js until this fix is released and we can publish a release based on it.

**Comment by romainmenke** [comment]
Hi!

This should be resolved with `v0.2.3`.

Please let us know if this issue persists.
