### ISSUE TITLE
Possible to use with vite?

### ISSUE THREAD

**Issue by dpschen** [mrhenry/core-web#856]
Just wanted to ask if it is possible to use this with vite?

**Comment by romainmenke** [comment]
@dpschen Not familiar with vite.
Is there a starter project?

Happy to assist in getting you setup!

**Comment by romainmenke** [comment]
At first glance it seems vite uses esbuild.
Is there a way to make it use babel?

Currently we have no plans to support esbuild as they lack support for too many old browser versions. This alone makes it not very interesting for us.

After they reach a stable `v1` and have better support (and docs) for Go plugins we might reconsider this.

Because of the way core-web needs to work (a lot of data to detect features) combined with how esbuild plugins work, would slow down your build to the point were it is unusable :/

**Comment by dpschen** [comment]
Hey @romainmenke,

thanks for looking into this =)

> Is there a starter project?
> Is there a way to make it use babel?

There is [@vitejs/plugin-legacy](https://github.com/vitejs/vite/tree/main/packages/plugin-legacy) which builds upon babel. Here a simple starter: https://stackblitz.com/edit/vitejs-vite-7dmbmw?file=vite.config.js&terminal=dev

**Comment by romainmenke** [comment]
Will try to take a look at this soon, but in the mean time you can try that plugin and see if this makes sense : https://github.com/mrhenry/core-web-example-script-tag/pull/1/files

It is an example pull request where babel config is added for `core-web`
The context is a webpack build but it might get you going.

**Comment by dpschen** [comment]
Will check that out, but won't be getting to this in the next days.

Thanks =)

**Comment by romainmenke** [comment]
@dpschen After a quick look it seems that `plugin-legacy` is not something that is extensible but a passes source code received from `vite` to `babel` and is intended to get `@babel/preset-env` working with `vite`.

To get `core-web` working with `vite` you would need to create a similar plugin that runs both `@babel/preset-env` and `core-web`.

We would advice against this as a stack setup this way would have the worst of both.
You would be limited by the feature set of both `vite`, `esbuild` and `babel` and build performance would be bad.

If really good cross browser and older browser support is important to you it might be better to use a stack with tools that have a proven track record in this (e.g. babel).

It would be nice if we could have support for `esbuild` and `vite` but we fear this will just make it easier for people to end up with a stack that is slow and has many bugs :/

Hopefully you understand :)
